version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    environment:
      - VITE_SOCKET_URL=http://localhost:10000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=10000
    volumes:
      - ./backend/uploads:/app/uploads 