services:
  - type: web
    name: chat-app-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: JWT_SECRET
        generateValue: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://<your-frontend>.vercel.app
    routes:
      - type: rewrite
        source: /*
        destination: /
    autoDeploy: true 