name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    name: Build & Test Backend

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      # Optionally, run backend tests if you have them
      # - name: Run backend tests
      #   run: npm test

      - name: Lint backend code
        run: npm run lint || echo "No lint script"

      - name: Build backend
        run: npm run build || echo "No build script"

  build-and-test-frontend:
    runs-on: ubuntu-latest
    name: Build & Test Frontend

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      # Optionally, run frontend tests if you have them
      # - name: Run frontend tests
      #   run: npm test

      - name: Lint frontend code
        run: npm run lint || echo "No lint script"

      - name: Build frontend
        run: npm run build
